dist: focal

services:
- docker

env:
  global:
  - BUNDLE_NAME=docker-archlinux-texlive-${TRAVIS_TAG:-$TRAVIS_BUILD_NUMBER}.tar.gz
  - IMAGE_NAME="bmgandre/docker-archlinux-texlive:${TRAVIS_TAG:-$TRAVIS_BUILD_NUMBER}"
  - secure: "KiIa1jN8z3zQmmvqpDw2RTkDBohN4cPfR+hVAC+Gr3j+8vMIfPLmt+GNzO1DCqBXUWME3AnpMJDVMYhskbDbxIq/9TXyY5HKx30SeekFprmZIkX8qItApfOsWea0zI4FOx6e3lTxim26VK3R25O8+Zkfoy9afoQH/CrQrb9mxGa+fTy2HgK7KJ5JBdAZ4mZZVaZkA+zE7/eRepn4ipeHG0hQLcuNlzH106VqDMHQvzRtNY9D8rJUTq4qtbatHPVrhdv3/0332AbVRleUHr45c59PFO0LKVTm0pHlZh/Pqgqo6iodvIWSH8Xiukr3PjY21rqfw4HHgCbDsNAk7aet4e8CAsJ7UMreU2nCWCX+cBQwBzt3pJDkRH367VHvSlt7Ua7gdB7M5Y02FZ/Nj7lzV2LsH/COL2Gk6FD+Wf6T0ea34UF3VEs929gAyvfWbFMz63bK9IrP5N9L+nuHJoVUmjIT8Q/y28PGN/4PMq2q76hDULFJ8Ov42+QIrdXq8xEzJae1cmVL80oYd3yM7ZGFp9tjrQ2RQ8MDi35jqaTNSv9tjHt8/jtgygETZA65rhbREtMDLAn6B6A9qHPgzmr4Pcc4CyBKtqVDo7sb1jsLwTpxVp/weeH5ahroCg4IeMd5CvW8DsY16eYccsiYYSSRyZMGOZZs5fQNguJBzdD2yHY="

before_script:
- docker version

script:
- docker build --tag "$IMAGE_NAME" --file Dockerfile .

after_success:
- docker images

before_deploy:
- tar -cvzf ${BUNDLE_NAME} *
- echo "deploying $BUNDLE_NAME to GitHub releases"

deploy:
- provider: releases
  api_key:
    secure: "xVxPCOXWe4xuCHd5kxNT4xONjcJwCYRjc3www905wDv8Pu9937MshJ4r71JnIPrTMsE7nXEm9NTFaQ5/J39lVPc8z9M5Tp1W/MPP+BIghPFtucq5ertXzJkhagYI7/vCjyowdQvOE2+Jpc+gv/DhzUn8eU9g24ay5EjxNI8fXFJbJJDqSKAbYxIRr6Cj/wwBU6VesWAWRZTtHeyfkIBAB9trJpHzTXrKfauyFBwIj2jPsyQHODyWrRsJFn47rUo8gKbCs+NKKBtQpkecQvNx91nwA3WurYyu7rGx5+Lm9WVrl8bDT88pGd7cieCUc4Qsd4E7DJeHbwpqAgnFOhvgZdTLcYsScGIz/KOg5+kZHlWT463lXvbqr/jy/3ji48XZhSGyGYl6Coaa3oEK0ftJhusXaQJhsv7DeduAzClwaeKE7L4O0GHRh7SCRrHJ53Z/psZCpkI0AoWowMRhn2jpJ0Oje5sM5Xi+okDwTQfjnj8IRTzcbYgXKen1EuHdlu7MGJI4lU+q5DSPS92ZI0dSxOMHVKZ2ckr7gY8tyFKq5Eug0TQZUjvQ6JyT6B7xXL7yqsbGdTPjlYpQFIie7aNWRxw18LErRFvrqnf592P7okMldripClORVaoyyXrm8XoDSyityAnWF60HakPL/3dBruYBlRmWtfUnNC0LwcbSF9c="
  file: "${BUNDLE_NAME}"
  on:
    tags: true
- provider: script
  script: bash dockerhub-deploy "$TRAVIS_TAG" "$DOCKER_USER" "$DOCKER_PASSWORD" "$IMAGE_NAME"
  on:
    tags: true
