dist: focal

services:
- docker

env:
  global:
  - BUNDLE_NAME=docker-archlinux-texlive-${TRAVIS_TAG:-$TRAVIS_BUILD_NUMBER}.tar.gz
  - IMAGE_NAME="bmgandre/docker-archlinux-texlive:${TRAVIS_TAG:-$TRAVIS_BUILD_NUMBER}"
  - secure: "DFnDzh7beN+VJYGddkxzhMKGfiTvAb95bkk4PqwZaUQbQ/vjhRCMqWoJIzFkSUicPVlmd28tyIK39Z+N3x70ti0BVoOUwLXMb47N++CJ3VIjVdqfMBzzwWhHUfxZNdT5HrDrJPUQTvEM4D4rkEocD0gcDq8w8t68QHbewu4NRXT0CrWC8vqJODubcpFQCPGHFjaAcNBqZZiKCEe9jR6xjlxaeWi5mojA3aXDNxU8WY1nS42jm60PGY7zw42lvp62GD0OfAf3A1Wq9aU8CV7krRpvnQmYJDx4I+CZbgEskDZ5YZDj1Pf4pflZZiulQpYjQuz6vr/CNTehqm2Wqz/EvWoo5RaP9pt8tf0WCJ77Wtwfs92oDxGB+YCCQibsL4sG78fpYtUB1xrYHW0xw07SFX+DBJm/K4pBMgs6W9WvQ1/p2sQPYd/0KOUd0haPuonYQN6EEt42BouUn56qNSc1uYZPQH2MMw8mQ+ln2MdMAWM4diKg4MDeI/Btp3McE+06NV7FOK7hs1p2Ju8jLAfGLWmOlk/RBELOhinbYcGn8Md7EgUCAPtq0EDSiODzRCfOheHIVTr3qb4TX3IlIuZwwMcZmMlSqTe1IFq/20OcOa2bB3HiWy4qFV+LrWsw0nSXXJJuXN1gZOSEidB7sIqknNEmpJ+0kMD9SjHzCnl9OG0="

before_script:
- docker version

script:
- docker build --tag "$IMAGE_NAME" --file Dockerfile .

after_success:
- docker images

before_deploy:
- tar -cvzf ${BUNDLE_NAME} *
- echo "deploying $BUNDLE_NAME to GitHub releases"

deploy:
- provider: releases
  api_key:
    secure: "noqzmvmqSw6IVj5SHGq6zPA0keuquM6OhtwhCUbohkPcN8SBJ5iHDTcCftSpjRMYZpj5lBeEPjnRtz+tbTVeOlp3+D420bqTYJsEwL8oeMQX6jXzuRKbDyi8Hcliz1FeXRH+papiBoQkop5s6TPhGOC9q6Ukh/X+nlJyoHWWxaDpPNjmOknNTfYwrfesBF4iQ4Nx03CMejGORjOcKE9Z7b2Di79uupTInionuU3lVKjk6ltTh9COC/G9wj8btTPM/h7jHd+y1Fz+K63H7a8ZYO8HSVKn7dR0q+PtPPWYXGrY5oU5tlZ54pRR01+R75awLswJ5VCAKoJo/32LL0QCemFUbOHqxC2ytn7c6b25AHMI7o2uT6WXmUpukiCIT4d6f+sFec8UJ6wttqCTcSrEHULkSaiBHZe4NU4aQzLw/YDuQBxvpzVze5/VBTPFMU7o2jZNxkFkkOkU+oKhiF77o7E0jeNkFuOG+HjC2BkwaaZTp6yPfHQ/E5T4E1h5asBRMEPciOjzAVj96gJqYqgcn+/A86yM2S9y4YMNRHHiJljQA1THWibAIDrtNVl/Yq79oW9aWUrA1cIGsthUOPipo6asYfIHW59PaBqF/p8i8dAU6REX62QP3Fz4oiDsgSkcijHLm3K5qqw+3+PmR44wVaNZMTWrWLd5DMUUTN6xGYw="
  file: "${BUNDLE_NAME}"
  on:
    tags: true
- provider: script
  script: bash dockerhub-deploy "$TRAVIS_TAG" "$DOCKER_USER" "$DOCKER_PASSWORD" "$IMAGE_NAME"
  on:
    tags: true
