dist: bionic

services:
- docker

env:
  global:
  - BUNDLE_NAME=docker-archlinux-texlive-${TRAVIS_TAG:-$TRAVIS_BUILD_NUMBER}.tar.gz
  - IMAGE_NAME="bmgandre/docker-archlinux-texlive:${TRAVIS_TAG:-$TRAVIS_BUILD_NUMBER}"

before_script:
- docker version

script:
- docker build --tag "$IMAGE_NAME" --file Dockerfile .

after_success:
- docker images

before_deploy:
- tar -cvzf ../${BUNDLE_NAME} *
- echo "deploying $BUNDLE_NAME to GitHub releases"

deploy:
  - provider: releases
    api_key:
      secure: RIkiaLnLqiGrqrbbVF51xLw/nxQkOxowY2FDn8MTxEWO1M2fuBfNBgcLz6M4LBUjo+Ej04y/BH4gd9g6gxjrE0jYZGrvptGi2Fi0A2MYYltewLzreCHPNHPtgXqPCoXDhDROItK+fONmAdibWd9Z/JRqFd+T9cLz91qCc2g1VTvjrA8ySlddFkrcIt7J9+W2GAdJJkouV/iU1Hc08TLykVcs/yuzK5tlZB5NN61z79anckKIp9RNc8bFKy8u/0Q67GUn4AEV5eHyYHlZEL/todIKJ2lPqua7tKjFeP50IR18594oQBAGOlZ+okhQf0ezbvAU0CvBuQtDz2NxBoPwhWKED1i6YnAN3CgcqEKkdLnL4pGCm/JroOFKMTLkMDgmikobYo+yEUfD4VsZbeoLcwylFBJ8azgNledTxLk5xcVM+h/mhFmYNmsxLRF+Or8md0e2Eyn4uSfu7npBe6INTLxikjNOZ4VgjPt5pf7y+OF3ylYHsWk7efatCszkAcsBdcjKy2X+a3njnEYogsAD/aCjprTh4tx7PCa/n8uiYjBluFI7G7EJ3SnwveeWJ4QJWGzo44AKbGLP1w95MzGEvkBk0emfN0DLp8komIrwwhKyhg9fYoJOcTwwrIOq9yyjqDnr849g6PL3csrlbJbQTIcgVxKB9WzFl6p08lHyj9A=
    file: "${BUNDLE_NAME}"
    on:
      tags: true
  - provider: script
    script: bash dockerhub-deploy "$TRAVIS_TAG" "$DOCKER_USER" "$DOCKER_PASSWORD" "$IMAGE_NAME"
    on:
      tags: true