name: Build and Publish

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build
        run: |
          docker build --tag bmgandre/docker-archlinux-texlive:${{ github.ref_name }} --file Dockerfile .
          docker push bmgandre/docker-archlinux-texlive
